### =============================================
### SISTEMA - STATUS
### =============================================

@HostAddress = http://localhost:7000

GET {{HostAddress}}/api/status
Accept: application/json

###
