-- Coluna1 10 (Produto Final) aceita Coluna2:
INSERT INTO Engenharia_GruposVinculos (GrupoPaiId, GrupoFilhoId, CriadoEm) VALUES
(1, 11, '2026-02-22T00:00:00'),
(1, 12, '2026-02-22T00:00:00');

-- Coluna1 20 (Conjunto Montado) aceita Coluna2:
INSERT INTO Engenharia_GruposVinculos (GrupoPaiId, GrupoFilhoId, CriadoEm) VALUES
(2, 13, '2026-02-22T00:00:00'),
(2, 14, '2026-02-22T00:00:00'),
(2, 15, '2026-02-22T00:00:00'),
(2, 16, '2026-02-22T00:00:00');

-- Coluna1 30 (Peça Fabricada) aceita Coluna2:
INSERT INTO Engenharia_GruposVinculos (GrupoPaiId, GrupoFilhoId, CriadoEm) VALUES
(3, 13, '2026-02-22T00:00:00'),
(3, 14, '2026-02-22T00:00:00'),
(3, 15, '2026-02-22T00:00:00');

-- Coluna1 40 (Peça Usinada) aceita Coluna2:
INSERT INTO Engenharia_GruposVinculos (GrupoPaiId, GrupoFilhoId, CriadoEm) VALUES
(4, 14, '2026-02-22T00:00:00'),
(4, 13, '2026-02-22T00:00:00');

-- Coluna1 50 (Comprado) aceita Coluna2:
INSERT INTO Engenharia_GruposVinculos (GrupoPaiId, GrupoFilhoId, CriadoEm) VALUES
(5, 18, '2026-02-22T00:00:00'),
(5, 19, '2026-02-22T00:00:00'),
(5, 20, '2026-02-22T00:00:00'),
(5, 21, '2026-02-22T00:00:00'),
(5, 23, '2026-02-22T00:00:00');

-- Coluna1 70 (Matéria Prima) aceita Coluna2:
INSERT INTO Engenharia_GruposVinculos (GrupoPaiId, GrupoFilhoId, CriadoEm) VALUES
(7, 24, '2026-02-22T00:00:00'),
(7, 25, '2026-02-22T00:00:00'),
(7, 26, '2026-02-22T00:00:00'),
(7, 27, '2026-02-22T00:00:00'),
(7, 28, '2026-02-22T00:00:00');

-- Coluna1 80 (Consumível) aceita Coluna2:
INSERT INTO Engenharia_GruposVinculos (GrupoPaiId, GrupoFilhoId, CriadoEm) VALUES
(8, 29, '2026-02-22T00:00:00'),
(8, 30, '2026-02-22T00:00:00'),
(8, 31, '2026-02-22T00:00:00'),
(8, 32, '2026-02-22T00:00:00'),
(8, 33, '2026-02-22T00:00:00');

-- Coluna1 90 (Embalagem) aceita Coluna2:
INSERT INTO Engenharia_GruposVinculos (GrupoPaiId, GrupoFilhoId, CriadoEm) VALUES
(9, 34, '2026-02-22T00:00:00'),
(9, 35, '2026-02-22T00:00:00');

-- Coluna2 PCP aceita Coluna3:
INSERT INTO Engenharia_GruposVinculos (GrupoPaiId, GrupoFilhoId, CriadoEm) VALUES
(11, 36, '2026-02-22T00:00:00'),
(11, 37, '2026-02-22T00:00:00');

-- Coluna2 EST aceita Coluna3:
INSERT INTO Engenharia_GruposVinculos (GrupoPaiId, GrupoFilhoId, CriadoEm) VALUES
(12, 38, '2026-02-22T00:00:00'),
(12, 39, '2026-02-22T00:00:00');

-- Coluna2 SGE aceita Coluna3:
INSERT INTO Engenharia_GruposVinculos (GrupoPaiId, GrupoFilhoId, CriadoEm) VALUES
(13, 38, '2026-02-22T00:00:00'),
(13, 39, '2026-02-22T00:00:00');

-- Coluna2 MEC aceita Coluna3:
INSERT INTO Engenharia_GruposVinculos (GrupoPaiId, GrupoFilhoId, CriadoEm) VALUES
(14, 38, '2026-02-22T00:00:00'),
(14, 39, '2026-02-22T00:00:00');

-- Coluna2 CHP aceita Coluna3:
INSERT INTO Engenharia_GruposVinculos (GrupoPaiId, GrupoFilhoId, CriadoEm) VALUES
(24, 40, '2026-02-22T00:00:00'),
(24, 41, '2026-02-22T00:00:00'),
(24, 42, '2026-02-22T00:00:00'),
(24, 43, '2026-02-22T00:00:00');

-- Coluna2 TUB aceita Coluna3:
INSERT INTO Engenharia_GruposVinculos (GrupoPaiId, GrupoFilhoId, CriadoEm) VALUES
(25, 44, '2026-02-22T00:00:00'),
(25, 45, '2026-02-22T00:00:00');

-- Coluna2 ROL aceita Coluna3:
INSERT INTO Engenharia_GruposVinculos (GrupoPaiId, GrupoFilhoId, CriadoEm) VALUES
(20, 47, '2026-02-22T00:00:00'),
(20, 48, '2026-02-22T00:00:00');

-- Coluna2 MOT aceita Coluna3:
INSERT INTO Engenharia_GruposVinculos (GrupoPaiId, GrupoFilhoId, CriadoEm) VALUES
(21, 46, '2026-02-22T00:00:00');

-- Coluna2 BRR aceita Coluna3:
INSERT INTO Engenharia_GruposVinculos (GrupoPaiId, GrupoFilhoId, CriadoEm) VALUES
(26, 41, '2026-02-22T00:00:00'),
(26, 42, '2026-02-22T00:00:00');