// <auto-generated />
using System;
using Api_ArjSys_Tcc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_ArjSys_Tcc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Api_ArjSys_Tcc.Models.Engenharia.EstruturaProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Posicao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdutoFilhoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdutoPaiId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoFilhoId");

                    b.HasIndex("ProdutoPaiId", "ProdutoFilhoId")
                        .IsUnique();

                    b.ToTable("Engenharia_EstruturasProdutos", (string)null);
                });

            modelBuilder.Entity("Api_ArjSys_Tcc.Models.Engenharia.GrupoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathDocumentos")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("QtdCaracteres")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Codigo", "Nivel")
                        .IsUnique();

                    b.ToTable("Engenharia_GruposProdutos", (string)null);
                });

            modelBuilder.Entity("Api_ArjSys_Tcc.Models.Engenharia.GrupoVinculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<int>("GrupoFilhoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrupoPaiId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GrupoFilhoId");

                    b.HasIndex("GrupoPaiId", "GrupoFilhoId")
                        .IsUnique();

                    b.ToTable("Engenharia_GruposVinculos", (string)null);
                });

            modelBuilder.Entity("Api_ArjSys_Tcc.Models.Engenharia.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoCompleta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Engenharia_Produtos", (string)null);
                });

            modelBuilder.Entity("Api_ArjSys_Tcc.Models.Engenharia.EstruturaProduto", b =>
                {
                    b.HasOne("Api_ArjSys_Tcc.Models.Engenharia.Produto", "ProdutoFilho")
                        .WithMany()
                        .HasForeignKey("ProdutoFilhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api_ArjSys_Tcc.Models.Engenharia.Produto", "ProdutoPai")
                        .WithMany()
                        .HasForeignKey("ProdutoPaiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProdutoFilho");

                    b.Navigation("ProdutoPai");
                });

            modelBuilder.Entity("Api_ArjSys_Tcc.Models.Engenharia.GrupoVinculo", b =>
                {
                    b.HasOne("Api_ArjSys_Tcc.Models.Engenharia.GrupoProduto", "GrupoFilho")
                        .WithMany()
                        .HasForeignKey("GrupoFilhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api_ArjSys_Tcc.Models.Engenharia.GrupoProduto", "GrupoPai")
                        .WithMany()
                        .HasForeignKey("GrupoPaiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrupoFilho");

                    b.Navigation("GrupoPai");
                });
#pragma warning restore 612, 618
        }
    }
}
